### ISSUE TITLE
Configure pylint to be ran on vscode.

### ISSUE THREAD

**Issue by dhmoon91** [dhmoon91/porobot#11]
We use pylint as main linter on status check upon PR. 

We are using `black` as autoformatter but `pylint` is not setup to run as base-linter. 

This is going to annoy the devs as they put up PR. 

Configure and update readme so `pylint` can run in our **Workspace**

**Comment by dhmoon91** [comment]
Maybe we could set pylint to run on prepush hook

git push -u origin mybranch
git push ->  pre-push hook run prepush commands -> push

**Comment by HelloFive** [comment]
Task:
- Add steps to setup&use pylint on vscode to README
- Setup pylint with pre-push hook

**Comment by jung1411** [comment]
@HelloFive this is done right?

**Comment by HelloFive** [comment]
Technically half done, since no steps for adding pylint on vscode is not added on README.
But I do not see this being priority.

**Comment by HelloFive** [comment]
@jung1411 Technically half done, since no steps for adding pylint on vscode is not added on README.
But I do not see this being priority.
Maybe worth mentioning in the standup and we can close this case due to lack of important and urgency.

**Comment by HelloFive** [comment]
2021-07-18:
- change back to pre-commit instead of pre-push
- find out difference btwn local pylint and GitHub > Action: pylint

**Comment by dhmoon91** [comment]
More stuff to look at; 
1) we have 3 places where `pylint` will/can be executed; local, on pre-commit hook (currently prepush), and on workflow. **ALL PRODUCE DIFFERENT RESULTS**
1) .pylintrc is not getting repected

Please figure out why.

**Comment by HelloFive** [comment]
Cause of different result of `pylint`:
- pre-commit hook:
Run pylint on the files that has been committed and does not run against other files
- local pylint run command: 
With `pylint $(git ls-files '*.py')` command, pylint run against all *.py files existing in the directory
- gituhb workflow: 
With `pylint --rcfile=.pylintrc 'ls -R|grep .py$|xargs'` command, pylint run against for all *.py files except the files under `alembic` and `db`

Difference of output can be viewed with this [diffchecker](https://www.diffchecker.com/eKmHTvnV)

**Comment by HelloFive** [comment]
Issue completed
