### ISSUE TITLE
Come up with name for our bot

### ISSUE THREAD

**Issue by jung1411** [dhmoon91/porobot#25]
- should be related to LOL
- concise

**Comment by jung1411** [comment]
List of all champion names
https://www.lol-smurfs.com/blog/league-of-legends-champions-list/
Some easy names include
- nunu
- annie
- lulu
- mumu    (amumu without an a)

**Comment by HelloFive** [comment]
-ahri
-ahriBot
-ashe

**Comment by jung1411** [comment]
- baron

**Comment by Ashe** [comment]
Can you please not use the @ symbol when brainstorming - you're pinging GitHub users :)

**Comment by HelloFive** [comment]
Oops! Sorry, I didn't realize that. Thank you for letting us know.
We will avoid using @ Symbol.

**Comment by jjaykim** [comment]
- teemo

**Comment by jung1411** [comment]
- Poro

**Comment by dhmoon91** [comment]
Going with PORo
