### ISSUE TITLE
No matching command; output message

### ISSUE THREAD

**Issue by dhmoon91** [dhmoon91/porobot#7]
No matching command; output message

**Comment by dhmoon91** [comment]
no matching command; 

Using `embed`
```
No matching command!
Please type `help` to see how to use
```
Later;
copy paste `help` command output.

**Comment by jjaykim** [comment]
> no matching command;
> 
> Using `embed`
> 
> ```
> No matching command!
> Please type `help` to see how to use
> ```
> 
> Later;
> copy paste `help` command output.

**Comment by dhmoon91** [comment]
@jjaykim if you are done with this, close the issue

**Comment by jjaykim** [comment]
I'm done with this issue. You can close it. Thank you
