### ISSUE TITLE
Each command should handle error gracefully.

### ISSUE THREAD

**Issue by dhmoon91** [dhmoon91/porobot#9]
eg;
!rank d4022;
No user found -> output proper message.

If !rank d4022 leonaldu
Output message to input one username

**Comment by jjaykim** [comment]
```
If !rank d4022 leonaldu
Output message to input one username
```
means output one by one user's rank? 
When I run `!rank d4022 leonaldu`  it shows only d4022's rank.

**Comment by dhmoon91** [comment]
Im saying each command should handle exception cases. 
eg; `rank` command should only take **one username**

so if user puts in more than one username as parameter, it should output error message that this command takes only one username

Also you should think of other cases that each command can not handle.

**Comment by jjaykim** [comment]
> Im saying each command should handle exception cases.
> eg; `rank` command should only take **one username**
> 
> so if user puts in more than one username as parameter, it should output error message that this command takes only one username
> 
> Also you should think of other cases that each command can not handle.

I understand now what you mean! Thank you ! :)
